### ISSUE TITLE
Please pull changes to incompletely vendor'd go.net

### ISSUE THREAD

**Issue by weingart** [hashicorp/go.net#2]
Is this software still supported?

https://github.com/hashicorp/go.net/pull/1

**Comment by ryanuber** [comment]
Hey @weingart,

We originally forked this due to this ticket: https://github.com/golang/go/issues/9047. The only place we use this library directly is in our mdns package, which imports ipv4 and ipv6 directly. The compile is broken now, though, so I'll merge in the changes to get it going again. At some point we need to revisit the go.net library and see about switching back to upstream.

**Comment by weingart** [comment]
Unfortunately, code.google.com is going away ASAP.  I'm not sure if an upstream for go.net currently exists.
